version: '3'
services:
  redis:
    image: redis:latest
    container_name: cache
    expose:
      - "6379"
  app:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    container_name: nodeApp
    links:
      - redis
    environment:
      - PORT=8080
      - TOKEN_SECRET=thisismysecret
    command:
      sh -c 'npm i && npm start'
